@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@baseURL = http://{{host}}

###

# @name login
POST {{baseURL}}/sessions
Content-Type: application/json

{
	"email": "jailson.cabelo@mail.com",
	"password": "123456"
}

###
@token = {{login.response.body.$.token}}

# @name list_providers
GET {{baseURL}}/providers
Authorization: Bearer {{token}}
Content-Type: application/json

###

# @name list_provider_appointments
GET {{baseURL}}/appointments/me?day=21&month=8&year=2020
Authorization: Bearer {{token}}
Content-Type: application/json
